package com.study.tddarchpractice.mock;

import com.study.tddarchpractice.common.domain.exception.ResourceNotFoundException;
import com.study.tddarchpractice.user.domain.User;
import com.study.tddarchpractice.user.domain.UserStatus;
import com.study.tddarchpractice.user.service.port.UserRepository;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicLong;

public class FakeUserRepository implements UserRepository {

    private final List<User> data = new ArrayList<>();
    private final AtomicLong autoGeneratedId = new AtomicLong(1);

    @Override
    public User getById(long id) {
        return data.stream()
                .filter(user -> user.getId() == id)
                .findAny()
                .orElseThrow(() -> new ResourceNotFoundException("Users", id));
    }


    @Override
    public Optional<User> findByIdAndStatus(long id, UserStatus userStatus) {
        return data.stream()
                .filter(user -> user.getId() == id && user.getStatus() == userStatus)
                .findAny();
    }

    @Override
    public Optional<User> findByEmailAndStatus(String email, UserStatus userStatus) {
        return data.stream()
                .filter(user -> user.getEmail().equals(email) && user.getStatus() == userStatus)
                .findAny();
    }

    @Override
    public User save(User user) {
        if (user.getId() == null) {
            User newUser = User.builder()
                    .id(autoGeneratedId.getAndIncrement())
                    .email(user.getEmail())
                    .nickname(user.getNickname())
                    .address(user.getAddress())
                    .certificationCode(user.getCertificationCode())
                    .status(user.getStatus())
                    .lastLoginAt(user.getLastLoginAt())
                    .build();
            data.add(newUser);
            return newUser;
        }
        data.removeIf(existing -> existing.getId().equals(user.getId()));
        data.add(user);
        return user;
    }

    @Override
    public Optional<User> findById(long id) {
        return data.stream()
                .filter(user -> user.getId() == id)
                .findAny();
    }


}
