package com.study.tddarchpractice.mock;

import com.study.tddarchpractice.common.domain.exception.ResourceNotFoundException;
import com.study.tddarchpractice.post.controller.port.PostService;
import com.study.tddarchpractice.post.domain.Post;
import com.study.tddarchpractice.post.domain.PostCreate;
import com.study.tddarchpractice.post.domain.PostUpdate;
import com.study.tddarchpractice.user.domain.User;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.atomic.AtomicLong;

public class FakePostService implements PostService {

    private final List<Post> data = new ArrayList<>();
    private final List<User> writers = new ArrayList<>();
    private final AtomicLong autoGeneratedId = new AtomicLong(1);

    public Post save(Post post) {
        if (post.getId() == null) {
            Post newPost = Post.builder()
                    .id(autoGeneratedId.getAndIncrement())
                    .content(post.getContent())
                    .createdAt(post.getCreatedAt())
                    .modifiedAt(post.getModifiedAt())
                    .writer(post.getWriter())
                    .build();
            data.add(newPost);
            return newPost;
        }
        data.removeIf(existing -> existing.getId().equals(post.getId()));
        data.add(post);
        return post;
    }

    public void addWriter(User writer) {
        writers.add(writer);
    }

    @Override
    public Post getById(long id) {
        return data.stream()
                .filter(post -> post.getId() == id)
                .findAny()
                .orElseThrow(() -> new ResourceNotFoundException("Posts", id));
    }

    @Override
    public Post create(PostCreate postCreate) {
        User writer = writers.stream()
                .filter(user -> user.getId() == postCreate.getWriterId())
                .findAny()
                .orElseThrow(() -> new ResourceNotFoundException("Users", postCreate.getWriterId()));
        Post post = Post.builder()
                .writer(writer)
                .content(postCreate.getContent())
                .createdAt(System.currentTimeMillis())
                .build();
        return save(post);
    }

    @Override
    public Post update(long id, PostUpdate postUpdate) {
        Post post = getById(id).update(postUpdate);
        return save(post);
    }
}
