package com.study.tddarchpractice.mock;

import com.study.tddarchpractice.post.domain.Post;
import com.study.tddarchpractice.post.service.port.PostRepository;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicLong;

public class FakePostRepository implements PostRepository {

    private final List<Post> data = new ArrayList<>();
    private final AtomicLong autoGeneratedId = new AtomicLong(1);

    @Override
    public Optional<Post> findById(Long id) {
        return data.stream()
                .filter(post -> post.getId().equals(id))
                .findAny();
    }

    @Override
    public Post save(Post post) {
        if (post.getId() == null) {
            Post newPost = Post.builder()
                    .id(autoGeneratedId.getAndIncrement())
                    .content(post.getContent())
                    .createdAt(post.getCreatedAt())
                    .modifiedAt(post.getModifiedAt())
                    .writer(post.getWriter())
                    .build();
            data.add(newPost);
            return newPost;
        }
        data.removeIf(existing -> existing.getId().equals(post.getId()));
        data.add(post);
        return post;
    }
}
