package com.study.tddarchpractice.mock;

import com.study.tddarchpractice.common.domain.exception.CertificationCodeNotMatchedException;
import com.study.tddarchpractice.common.domain.exception.ResourceNotFoundException;
import com.study.tddarchpractice.user.controller.port.UserService;
import com.study.tddarchpractice.user.domain.User;
import com.study.tddarchpractice.user.domain.UserCreate;
import com.study.tddarchpractice.user.domain.UserStatus;
import com.study.tddarchpractice.user.domain.UserUpdate;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.atomic.AtomicLong;

public class FakeUserService implements UserService {

    private final List<User> data = new ArrayList<>();
    private final AtomicLong autoGeneratedId = new AtomicLong(1);

    public User save(User user) {
        if (user.getId() == null) {
            User newUser = User.builder()
                    .id(autoGeneratedId.getAndIncrement())
                    .email(user.getEmail())
                    .nickname(user.getNickname())
                    .address(user.getAddress())
                    .certificationCode(user.getCertificationCode())
                    .status(user.getStatus())
                    .lastLoginAt(user.getLastLoginAt())
                    .build();
            data.add(newUser);
            return newUser;
        }
        data.removeIf(existing -> existing.getId().equals(user.getId()));
        data.add(user);
        return user;
    }

    @Override
    public User getByEmail(String email) {
        return data.stream()
                .filter(user -> user.getEmail().equals(email))
                .findAny()
                .orElseThrow(() -> new ResourceNotFoundException("Users", email));
    }

    @Override
    public User getById(long id) {
        return data.stream()
                .filter(user -> user.getId() == id)
                .findAny()
                .orElseThrow(() -> new ResourceNotFoundException("Users", id));
    }

    @Override
    public User create(UserCreate userCreate) {
        User user = User.builder()
                .email(userCreate.getEmail())
                .nickname(userCreate.getNickname())
                .address(userCreate.getAddress())
                .certificationCode("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                .status(UserStatus.PENDING)
                .build();
        return save(user);
    }

    @Override
    public User update(long id, UserUpdate userUpdate) {
        User user = getById(id).update(userUpdate);
        return save(user);
    }

    @Override
    public void login(long id) {
        User user = getById(id);
        save(user.login(new TestClockHolder(1678530673958L)));
    }

    @Override
    public void verifyEmail(long id, String certificationCode) {
        User user = getById(id);
        if (!certificationCode.equals(user.getCertificationCode())) {
            throw new CertificationCodeNotMatchedException();
        }
        save(user.certificate(certificationCode));
    }
}
